target:
- target_y
continuous_cols:
- f_0
- f_1
- f_2
- f_3
- f_4
- f_5
- f_6
- f_7
- f_8
- f_9
- f_10
- f_11
- f_12
- f_13
- f_14
- f_15
- f_16
- f_17
- f_18
- f_19
- f_20
- f_21
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
pickle_protocol: 2
dataloader_kwargs: {}
task: regression
head: LinearHead
head_config:
  layers: ''
embedding_dims: []
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001223115992323341
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.node
_model_name: NODEModel
_backbone_name: NODEBackbone
_config_name: NodeConfig
num_layers: 1
num_trees: 2048
additional_tree_output_dim: 3
depth: 6
choice_function: entmax15
bin_function: entmoid15
max_features: null
input_dropout: 0.0
initialize_response: normal
initialize_selection_logits: uniform
threshold_init_beta: 1.0
threshold_init_cutoff: 1.0
batch_size: 64
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 19
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: none
precision: '32'
trainer_kwargs:
  enable_model_summary: false
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
lr_scheduler_interval: epoch
categorical_dim: 0
continuous_dim: 22
output_dim: 1
output_cardinality: null
categorical_cardinality: []
embedded_cat_dim: 0
